### PR TITLE
feat: added navbar and fix auth context

### PR DESCRIPTION
**Pull request by richard483**
* + ada pembetulan dikit di context

### CODE REVIEW

**Review by youhane — CHANGES_REQUESTED** [review]
reponsivenya belom gan, sisanya oke, ntapp

**Comment by richard483** [comment]
moga instant

**Comment by youhane** [comment]
- [ ] navbar resizing not properly
- [x] logout button still visible when as guest mode
- [ ] z index of navbar not right
- [ ] navbar outeroverlay (item2 belakangnya) ga pas
- [x] animation for navbar should be sliding not fading
- [ ] animation on navbar dissapearing still not here yet either
- [ ] navbar contents not sized properly

**Comment by youhane** [comment]
styling sama animasinya kurang mulus si cad, gw benerin aja ya

**Comment by youhane** [comment]
styling harusnya kelar, besok gw cek logic contextnya

**Comment by youhane** [comment]
navbar on logged in state still buggy, trying to debug and fix it

**Pull request merged**
